name: Manala CI for "elao.app" recipe
description: 'Provision & run commands inside a Manala CI environment with "elao.app" recipe'
author: Elao

branding:
  icon: 'terminal'
  color: 'orange'

inputs:
  cmd:
    description: 'Command to execute'
    required: false
    default: 'echo "Manala CI environment setup is done and ready to run your commands!"'

  working-directory:
    description: 'Working dir for the command, relative to your workspace dir'
    required: false

  docker-compose-file:
    description: 'The docker-compose.yaml file used to start services'
    required: false
    default: '.manala/github/docker-compose.yaml'

runs:
  using: 'composite'
  steps:

    - name: 'Escape cmd shell script by dumping into an executable file'
      shell: bash
      run: |
        echo "${{ inputs.cmd }}" > ${{ inputs.working-directory || github.workspace }}/manala_ci_cmd.sh
        chmod +x ${{ inputs.working-directory || github.workspace }}/manala_ci_cmd.sh

    - name: 'Prepare'
      shell: bash
      run: |
        docker_compose="docker-compose --file ${{ inputs.docker-compose-file }}"

        echo "::group::Run services if not already up"
          [ -z "$SSH_AUTH_SOCK"] && touch ~/ssh-agent
          MANALA_CI_UID=$(id -u) MANALA_CI_GID=$(id -g) $docker_compose up --detach
          docker ps --all
        echo "::endgroup::"

    - name: 'Execute cmd in the Manala CI environment'
      id: execute-cmd
      shell: bash
      env:
        # "The input device is not a TTY" (this env var)
        # "ValueError: I/O operation on closed file." (-T)
        # See https://github.com/docker/compose/issues/5696
        COMPOSE_INTERACTIVE_NO_CLI: '1'
      run: |
        docker_compose="docker-compose --file ${{ inputs.docker-compose-file }}"

        $docker_compose \
          exec \
          -T \
          -w /srv/app/${{ inputs.working-directory }} \
          manala_ci \
          bash -c "./manala_ci_cmd.sh"

    - name: 'Clean'
      shell: bash
      run: rm ${{ inputs.working-directory || github.workspace }}/manala_ci_cmd.sh
